[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false

[global]
logLevel = "info"
[theme]
base = "light"
primaryColor = "#5C2A21"
backgroundColor = "#FAFAF5"
secondaryBackgroundColor = "#F3EDE4"
textColor = "#2B211D"
font = "sans serif"
